export const SILENCE_APPEAL = '[Silence]';

export const GET_SILENCE_APPEALS = `${SILENCE_APPEAL} GET_SILENCE_APPEALS`;
export const SET_SILENCE_APPEALS = `${SILENCE_APPEAL} SET_SILENCE_APPEALS`;
export const CREATE_SILENCE_APPEAL = `${SILENCE_APPEAL} CREATE_SILENCE_APPEAL`;
export const ADD_SILENCE_APPEAL = `${SILENCE_APPEAL} ADD_SILENCE_APPEAL`;
export const DOWNLOAD = `${SILENCE_APPEAL} DOWNLOAD`;
export const ABORT_APPEAL = `${SILENCE_APPEAL} ABORT`;
export const SEARCH = `${SILENCE_APPEAL} SEARCH`;
export const SET_SEARCH = `${SILENCE_APPEAL} SET_SEARCH`;