export const DECISION_APPEAL = '[Decision]';
export const GET_DECISION_APPEALS = `${DECISION_APPEAL} GET_DECISION_APPEAL`;
export const SET_DECISION_APPEALS = `${DECISION_APPEAL} SET_DECISION_APPEAL`;

