export const APPEAL_ANNOUNCEMENT = '[APPEAL_ANNOUNCEMENT]';
export const GET_APPEAL_ANNOUNCEMENTS = `${APPEAL_ANNOUNCEMENT} GET_APPEAL_ANNOUNCEMENTS`;
export const SET_APPEAL_ANNOUNCEMENTS = `${APPEAL_ANNOUNCEMENT} SET_APPEAL_ANNOUNCEMENTS`;
export const CREATE_ANSWER = `${APPEAL_ANNOUNCEMENT} CREATE_ANSWER`;
